//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tupojj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Здание.
    /// </summary>
    // *** Start programmer edit section *** (Здание CustomAttributes)

    // *** End programmer edit section *** (Здание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗданиеE", new string[] {
            "nomer as \'Nomer\'",
            "этаж as \'Этаж\'",
            "Город as \'Город\'",
            "Город.name as \'Name\'"}, Hidden=new string[] {
            "Город.name"})]
    [MasterViewDefineAttribute("ЗданиеE", "Город", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "name")]
    [View("ЗданиеL", new string[] {
            "nomer as \'Nomer\'",
            "этаж as \'Этаж\'",
            "Город.name as \'Name\'"})]
    public class Здание : ICSSoft.STORMNET.DataObject
    {
        
        private int fnomer;
        
        private int fэтаж;
        
        private IIS.Tupojj.Город fГород;
        
        // *** Start programmer edit section *** (Здание CustomMembers)

        // *** End programmer edit section *** (Здание CustomMembers)

        
        /// <summary>
        /// nomer.
        /// </summary>
        // *** Start programmer edit section *** (Здание.nomer CustomAttributes)

        // *** End programmer edit section *** (Здание.nomer CustomAttributes)
        public virtual int nomer
        {
            get
            {
                // *** Start programmer edit section *** (Здание.nomer Get start)

                // *** End programmer edit section *** (Здание.nomer Get start)
                int result = this.fnomer;
                // *** Start programmer edit section *** (Здание.nomer Get end)

                // *** End programmer edit section *** (Здание.nomer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.nomer Set start)

                // *** End programmer edit section *** (Здание.nomer Set start)
                this.fnomer = value;
                // *** Start programmer edit section *** (Здание.nomer Set end)

                // *** End programmer edit section *** (Здание.nomer Set end)
            }
        }
        
        /// <summary>
        /// этаж.
        /// </summary>
        // *** Start programmer edit section *** (Здание.этаж CustomAttributes)

        // *** End programmer edit section *** (Здание.этаж CustomAttributes)
        public virtual int этаж
        {
            get
            {
                // *** Start programmer edit section *** (Здание.этаж Get start)

                // *** End programmer edit section *** (Здание.этаж Get start)
                int result = this.fэтаж;
                // *** Start programmer edit section *** (Здание.этаж Get end)

                // *** End programmer edit section *** (Здание.этаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.этаж Set start)

                // *** End programmer edit section *** (Здание.этаж Set start)
                this.fэтаж = value;
                // *** Start programmer edit section *** (Здание.этаж Set end)

                // *** End programmer edit section *** (Здание.этаж Set end)
            }
        }
        
        /// <summary>
        /// Здание.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Город CustomAttributes)

        // *** End programmer edit section *** (Здание.Город CustomAttributes)
        [PropertyStorage(new string[] {
                "Город"})]
        [NotNull()]
        public virtual IIS.Tupojj.Город Город
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Город Get start)

                // *** End programmer edit section *** (Здание.Город Get start)
                IIS.Tupojj.Город result = this.fГород;
                // *** Start programmer edit section *** (Здание.Город Get end)

                // *** End programmer edit section *** (Здание.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Город Set start)

                // *** End programmer edit section *** (Здание.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (Здание.Город Set end)

                // *** End programmer edit section *** (Здание.Город Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗданиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеE", typeof(IIS.Tupojj.Здание));
                }
            }
            
            /// <summary>
            /// "ЗданиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеL", typeof(IIS.Tupojj.Здание));
                }
            }
        }
    }
}
